use accordions in subscription view
tanzquotient/website pull request #288
Opened 2024-05-05 21:08 UTC by daviddavidgit

2024-05-06 07:03 UTC, dsparber requested changes

2024-05-06 07:10 UTC, thgoebel commented on courses/templates/user/user_courses.html
> +        {% if subscriptions %}
I like it. I want to “collapse all” to quickly skim through the list, but sometimes I want to “expand all” to slowly scroll through and read it without having to click every single time.

2024-05-06 07:13 UTC, dsparber commented on courses/templates/user/user_courses.html
> +        {% if subscriptions %}
Okay, fair enough, but let's have smaller and less prominent buttons for it.
The current ones feel a bit too much.

2024-05-06 07:15 UTC, thgoebel commented on templates/basis.html
> +<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
Yep, ideally only on the subpage where it is needed. Same for the accordions.js

2024-05-06 07:18 UTC, thgoebel commented
Other than that, it generally looks nice, thanks for having a go at this!
I have 6.5 years worth of courses, so really appreciated 😄

2024-05-06 08:47 UTC, daviddavidgit commented on static/css/user_courses.css
> +.user-course-expand-button {
done

2024-05-06 08:47 UTC, daviddavidgit commented on static/css/user_courses.css
> +.user-course-accordion {
done

2024-05-06 08:47 UTC, daviddavidgit commented on static/css/user_courses.css
> +.accordion-header-subscription .badge {
done

2024-05-06 08:48 UTC, daviddavidgit commented on templates/basis.html
> +    <link rel="stylesheet" href="{% static "css/user_courses.css" %}">
done

2024-05-06 09:43 UTC, daviddavidgit commented on courses/templates/user/user_courses.html
> +        {% if subscriptions %}
done, I used the `btn-link` class.

2024-05-06 09:52 UTC, daviddavidgit commented on templates/basis.html
> +<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
done

2024-05-06 10:00 UTC, daviddavidgit commented on courses/templates/user/snippets/subscription.html
> +        <div class="accordion-body fs-6 py-4">
Since it is only used once, I would leave it as it is, if that is ok?

2024-05-06 10:03 UTC, thgoebel commented on courses/templates/user/snippets/subscription.html
> +        <div class="accordion-body fs-6 py-4">
Sure, I was mostly concerned with readability, I don’t mind.

Did you already push btw?

2024-05-06 10:06 UTC, thgoebel commented on courses/templates/courses/snippets/period.html
> +{{ from|date:"d. N Y" }} - {{ to|date:"d. N Y" }}
👍 
I actually like having the year in the course details. This way, if you view old course details (via Course Archive or via your profile) you see the year. And it doesn’t hurt to have it for the current year.

2024-05-06 10:11 UTC, daviddavidgit commented
I forget to insert translations for the expand/collapse button. I tried to add the translations, but it did not work. If someone have a look at it, that would be great :)

2024-05-06 10:13 UTC, thgoebel commented on static/css/user_courses.css
> +.user-course-accordion {
delete not simply uncomment :)

2024-05-06 10:13 UTC, thgoebel commented on courses/templates/user/user_courses.html
> +    <script src="{% static "subscriptions_accordions.js" %}"></script>
Do you also need to add jquery here?

2024-05-06 10:52 UTC, daviddavidgit commented on courses/templates/user/user_courses.html
> +    <script src="{% static "subscriptions_accordions.js" %}"></script>
It does not seem to be the case.

2024-05-06 10:53 UTC, daviddavidgit commented on static/css/user_courses.css
> +.user-course-accordion {
ups, may bad, done

2024-05-06 13:03 UTC, dsparber commented on courses/templates/courses/snippets/period.html
> +{{ from|date:"d. N Y" }} - {{ to|date:"d. N Y" }}
I think it breaks the layout of the course list, as the year takes too much space. I.e. we might have way more line wraps.

2024-05-07 06:59 UTC, dsparber commented on courses/templates/courses/snippets/period.html
> +{{ from|date:"d. N Y" }} - {{ to|date:"d. N Y" }}
I saw this snipped is included in `lessons_compact.html`. The year should not be displayed there.

2024-05-07 07:03 UTC, dsparber commented
The layout for each course is broken now. It's less compact. Please revert back to the previous layout, thanks! 

![image](https://github.com/tanzquotient/website/assets/8910833/ba721637-5f8e-4fb4-a491-eecd2a93d38c)

![image](https://github.com/tanzquotient/website/assets/8910833/12805310-0b6a-417c-b023-8ea9ca4bc778)

2024-05-07 07:08 UTC, dsparber commented on courses/templates/courses/snippets/period.html
> +{{ from|date:"d. N Y" }} - {{ to|date:"d. N Y" }}
On my phone, the course list now needs an additional row per course. Please make sure to roll back the change there. 

![image](https://github.com/tanzquotient/website/assets/8910833/034f8d9a-8f9b-4672-96c3-5b5620b6c547)

![image](https://github.com/tanzquotient/website/assets/8910833/78a18c7a-1458-47c7-a1ae-2312288a6946)

2024-05-18 15:42 UTC, daviddavidgit commented on courses/templates/courses/snippets/period.html
> +{{ from|date:"d. N Y" }} - {{ to|date:"d. N Y" }}
done

2024-05-21 21:23 UTC, dsparber commented
Manually merged

2024-05-21 21:23 UTC, closed without merging